// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.24.4
// source: rpcpb/services.proto

package rpcpb

import (
	clientpb "github.com/bishopfox/sliver/protobuf/clientpb"
	commonpb "github.com/bishopfox/sliver/protobuf/commonpb"
	sliverpb "github.com/bishopfox/sliver/protobuf/sliverpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpcpb_services_proto protoreflect.FileDescriptor

const file_rpcpb_services_proto_rawDesc = "" +
	"\n" +
	"\x14rpcpb/services.proto\x12\x05rpcpb\x1a\x15commonpb/common.proto\x1a\x15sliverpb/sliver.proto\x1a\x15clientpb/client.proto2\xafV\n" +
	"\tSliverRPC\x120\n" +
	"\n" +
	"GetVersion\x12\x0f.commonpb.Empty\x1a\x11.clientpb.Version\x127\n" +
	"\tClientLog\x12\x17.clientpb.ClientLogData\x1a\x0f.commonpb.Empty(\x01\x124\n" +
	"\fGetOperators\x12\x0f.commonpb.Empty\x1a\x13.clientpb.Operators\x12*\n" +
	"\x04Kill\x12\x11.sliverpb.KillReq\x1a\x0f.commonpb.Empty\x12>\n" +
	"\vReconfigure\x12\x18.sliverpb.ReconfigureReq\x1a\x15.sliverpb.Reconfigure\x12.\n" +
	"\x06Rename\x12\x13.clientpb.RenameReq\x1a\x0f.commonpb.Empty\x122\n" +
	"\vGetSessions\x12\x0f.commonpb.Empty\x1a\x12.clientpb.Sessions\x123\n" +
	"\fMonitorStart\x12\x0f.commonpb.Empty\x1a\x12.commonpb.Response\x12/\n" +
	"\vMonitorStop\x12\x0f.commonpb.Empty\x1a\x0f.commonpb.Empty\x12C\n" +
	"\x11MonitorListConfig\x12\x0f.commonpb.Empty\x1a\x1d.clientpb.MonitoringProviders\x12D\n" +
	"\x10MonitorAddConfig\x12\x1c.clientpb.MonitoringProvider\x1a\x12.commonpb.Response\x12D\n" +
	"\x10MonitorDelConfig\x12\x1c.clientpb.MonitoringProvider\x1a\x12.commonpb.Response\x12E\n" +
	"\x11StartMTLSListener\x12\x19.clientpb.MTLSListenerReq\x1a\x15.clientpb.ListenerJob\x12A\n" +
	"\x0fStartWGListener\x12\x17.clientpb.WGListenerReq\x1a\x15.clientpb.ListenerJob\x12C\n" +
	"\x10StartDNSListener\x12\x18.clientpb.DNSListenerReq\x1a\x15.clientpb.ListenerJob\x12F\n" +
	"\x12StartHTTPSListener\x12\x19.clientpb.HTTPListenerReq\x1a\x15.clientpb.ListenerJob\x12E\n" +
	"\x11StartHTTPListener\x12\x19.clientpb.HTTPListenerReq\x1a\x15.clientpb.ListenerJob\x120\n" +
	"\n" +
	"GetBeacons\x12\x0f.commonpb.Empty\x1a\x11.clientpb.Beacons\x12/\n" +
	"\tGetBeacon\x12\x10.clientpb.Beacon\x1a\x10.clientpb.Beacon\x12-\n" +
	"\bRmBeacon\x12\x10.clientpb.Beacon\x1a\x0f.commonpb.Empty\x129\n" +
	"\x0eGetBeaconTasks\x12\x10.clientpb.Beacon\x1a\x15.clientpb.BeaconTasks\x12B\n" +
	"\x14GetBeaconTaskContent\x12\x14.clientpb.BeaconTask\x1a\x14.clientpb.BeaconTask\x12>\n" +
	"\x10CancelBeaconTask\x12\x14.clientpb.BeaconTask\x1a\x14.clientpb.BeaconTask\x12N\n" +
	" UpdateBeaconIntegrityInformation\x12\x19.clientpb.BeaconIntegrity\x1a\x0f.commonpb.Empty\x12*\n" +
	"\aGetJobs\x12\x0f.commonpb.Empty\x1a\x0e.clientpb.Jobs\x122\n" +
	"\aKillJob\x12\x14.clientpb.KillJobReq\x1a\x11.clientpb.KillJob\x127\n" +
	"\vRestartJobs\x12\x17.clientpb.RestartJobReq\x1a\x0f.commonpb.Empty\x12O\n" +
	"\x16StartTCPStagerListener\x12\x1b.clientpb.StagerListenerReq\x1a\x18.clientpb.StagerListener\x12)\n" +
	"\aLootAdd\x12\x0e.clientpb.Loot\x1a\x0e.clientpb.Loot\x12)\n" +
	"\x06LootRm\x12\x0e.clientpb.Loot\x1a\x0f.commonpb.Empty\x12,\n" +
	"\n" +
	"LootUpdate\x12\x0e.clientpb.Loot\x1a\x0e.clientpb.Loot\x12-\n" +
	"\vLootContent\x12\x0e.clientpb.Loot\x1a\x0e.clientpb.Loot\x12-\n" +
	"\aLootAll\x12\x0f.commonpb.Empty\x1a\x11.clientpb.AllLoot\x12/\n" +
	"\x05Creds\x12\x0f.commonpb.Empty\x1a\x15.clientpb.Credentials\x122\n" +
	"\bCredsAdd\x12\x15.clientpb.Credentials\x1a\x0f.commonpb.Empty\x121\n" +
	"\aCredsRm\x12\x15.clientpb.Credentials\x1a\x0f.commonpb.Empty\x125\n" +
	"\vCredsUpdate\x12\x15.clientpb.Credentials\x1a\x0f.commonpb.Empty\x129\n" +
	"\vGetCredByID\x12\x14.clientpb.Credential\x1a\x14.clientpb.Credential\x12A\n" +
	"\x12GetCredsByHashType\x12\x14.clientpb.Credential\x1a\x15.clientpb.Credentials\x12J\n" +
	"\x1bGetPlaintextCredsByHashType\x12\x14.clientpb.Credential\x1a\x15.clientpb.Credentials\x12@\n" +
	"\x12CredsSniffHashType\x12\x14.clientpb.Credential\x1a\x14.clientpb.Credential\x12,\n" +
	"\x05Hosts\x12\x0f.commonpb.Empty\x1a\x12.clientpb.AllHosts\x12&\n" +
	"\x04Host\x12\x0e.clientpb.Host\x1a\x0e.clientpb.Host\x12)\n" +
	"\x06HostRm\x12\x0e.clientpb.Host\x1a\x0f.commonpb.Empty\x12+\n" +
	"\tHostIOCRm\x12\r.clientpb.IOC\x1a\x0f.commonpb.Empty\x12<\n" +
	"\bHostScan\x12\x15.clientpb.HostScanReq\x1a\x19.clientpb.HostScanResults\x125\n" +
	"\bGenerate\x12\x15.clientpb.GenerateReq\x1a\x12.clientpb.Generate\x12R\n" +
	"\x10GenerateExternal\x12\x1d.clientpb.ExternalGenerateReq\x1a\x1f.clientpb.ExternalImplantConfig\x12M\n" +
	"\x19GenerateExternalSaveBuild\x12\x1f.clientpb.ExternalImplantBinary\x1a\x0f.commonpb.Empty\x12Y\n" +
	"\x1eGenerateExternalGetBuildConfig\x12\x16.clientpb.ImplantBuild\x1a\x1f.clientpb.ExternalImplantConfig\x12?\n" +
	"\rGenerateStage\x12\x1a.clientpb.GenerateStageReq\x1a\x12.clientpb.Generate\x12?\n" +
	"\x11StageImplantBuild\x12\x19.clientpb.ImplantStageReq\x1a\x0f.commonpb.Empty\x12=\n" +
	"\x11GetHTTPC2Profiles\x12\x0f.commonpb.Empty\x1a\x17.clientpb.HTTPC2Configs\x12H\n" +
	"\x16GetHTTPC2ProfileByName\x12\x16.clientpb.C2ProfileReq\x1a\x16.clientpb.HTTPC2Config\x12?\n" +
	"\x11SaveHTTPC2Profile\x12\x19.clientpb.HTTPC2ConfigReq\x1a\x0f.commonpb.Empty\x127\n" +
	"\x0fBuilderRegister\x12\x11.clientpb.Builder\x1a\x0f.clientpb.Event0\x01\x122\n" +
	"\x0eBuilderTrigger\x12\x0f.clientpb.Event\x1a\x0f.commonpb.Empty\x12/\n" +
	"\bBuilders\x12\x0f.commonpb.Empty\x1a\x12.clientpb.Builders\x12J\n" +
	"\x12GetCertificateInfo\x12\x19.clientpb.CertificatesReq\x1a\x19.clientpb.CertificateInfo\x12A\n" +
	"\x14CrackstationRegister\x12\x16.clientpb.Crackstation\x1a\x0f.clientpb.Event0\x01\x127\n" +
	"\x13CrackstationTrigger\x12\x0f.clientpb.Event\x1a\x0f.commonpb.Empty\x12B\n" +
	"\x15CrackstationBenchmark\x12\x18.clientpb.CrackBenchmark\x1a\x0f.commonpb.Empty\x129\n" +
	"\rCrackstations\x12\x0f.commonpb.Empty\x1a\x17.clientpb.Crackstations\x129\n" +
	"\rCrackTaskByID\x12\x13.clientpb.CrackTask\x1a\x13.clientpb.CrackTask\x127\n" +
	"\x0fCrackTaskUpdate\x12\x13.clientpb.CrackTask\x1a\x0f.commonpb.Empty\x12;\n" +
	"\x0eCrackFilesList\x12\x13.clientpb.CrackFile\x1a\x14.clientpb.CrackFiles\x12;\n" +
	"\x0fCrackFileCreate\x12\x13.clientpb.CrackFile\x1a\x13.clientpb.CrackFile\x12A\n" +
	"\x14CrackFileChunkUpload\x12\x18.clientpb.CrackFileChunk\x1a\x0f.commonpb.Empty\x12L\n" +
	"\x16CrackFileChunkDownload\x12\x18.clientpb.CrackFileChunk\x1a\x18.clientpb.CrackFileChunk\x129\n" +
	"\x11CrackFileComplete\x12\x13.clientpb.CrackFile\x1a\x0f.commonpb.Empty\x127\n" +
	"\x0fCrackFileDelete\x12\x13.clientpb.CrackFile\x1a\x0f.commonpb.Empty\x129\n" +
	"\n" +
	"Regenerate\x12\x17.clientpb.RegenerateReq\x1a\x12.clientpb.Generate\x129\n" +
	"\rImplantBuilds\x12\x0f.commonpb.Empty\x1a\x17.clientpb.ImplantBuilds\x12:\n" +
	"\x12DeleteImplantBuild\x12\x13.clientpb.DeleteReq\x1a\x0f.commonpb.Empty\x12/\n" +
	"\bCanaries\x12\x0f.commonpb.Empty\x1a\x12.clientpb.Canaries\x12C\n" +
	"\x16GenerateWGClientConfig\x12\x0f.commonpb.Empty\x1a\x18.clientpb.WGClientConfig\x129\n" +
	"\x10GenerateUniqueIP\x12\x0f.commonpb.Empty\x1a\x14.clientpb.UniqueWGIP\x12=\n" +
	"\x0fImplantProfiles\x12\x0f.commonpb.Empty\x1a\x19.clientpb.ImplantProfiles\x12<\n" +
	"\x14DeleteImplantProfile\x12\x13.clientpb.DeleteReq\x1a\x0f.commonpb.Empty\x12H\n" +
	"\x12SaveImplantProfile\x12\x18.clientpb.ImplantProfile\x1a\x18.clientpb.ImplantProfile\x12A\n" +
	"\fShellcodeRDI\x12\x19.clientpb.ShellcodeRDIReq\x1a\x16.clientpb.ShellcodeRDI\x122\n" +
	"\vGetCompiler\x12\x0f.commonpb.Empty\x1a\x12.clientpb.Compiler\x12K\n" +
	"\x10ShellcodeEncoder\x12\x1c.clientpb.ShellcodeEncodeReq\x1a\x19.clientpb.ShellcodeEncode\x12E\n" +
	"\x13ShellcodeEncoderMap\x12\x0f.commonpb.Empty\x1a\x1d.clientpb.ShellcodeEncoderMap\x12A\n" +
	"\x11TrafficEncoderMap\x12\x0f.commonpb.Empty\x1a\x1b.clientpb.TrafficEncoderMap\x12L\n" +
	"\x11TrafficEncoderAdd\x12\x18.clientpb.TrafficEncoder\x1a\x1d.clientpb.TrafficEncoderTests\x12=\n" +
	"\x10TrafficEncoderRm\x12\x18.clientpb.TrafficEncoder\x1a\x0f.commonpb.Empty\x12/\n" +
	"\bWebsites\x12\x0f.commonpb.Empty\x1a\x12.clientpb.Websites\x12/\n" +
	"\aWebsite\x12\x11.clientpb.Website\x1a\x11.clientpb.Website\x123\n" +
	"\rWebsiteRemove\x12\x11.clientpb.Website\x1a\x0f.commonpb.Empty\x12C\n" +
	"\x11WebsiteAddContent\x12\x1b.clientpb.WebsiteAddContent\x1a\x11.clientpb.Website\x12F\n" +
	"\x14WebsiteUpdateContent\x12\x1b.clientpb.WebsiteAddContent\x1a\x11.clientpb.Website\x12I\n" +
	"\x14WebsiteRemoveContent\x12\x1e.clientpb.WebsiteRemoveContent\x1a\x11.clientpb.Website\x12&\n" +
	"\x04Ping\x12\x0e.sliverpb.Ping\x1a\x0e.sliverpb.Ping\x12#\n" +
	"\x02Ps\x12\x0f.sliverpb.PsReq\x1a\f.sliverpb.Ps\x128\n" +
	"\tTerminate\x12\x16.sliverpb.TerminateReq\x1a\x13.sliverpb.Terminate\x125\n" +
	"\bIfconfig\x12\x15.sliverpb.IfconfigReq\x1a\x12.sliverpb.Ifconfig\x122\n" +
	"\aNetstat\x12\x14.sliverpb.NetstatReq\x1a\x11.sliverpb.Netstat\x12#\n" +
	"\x02Ls\x12\x0f.sliverpb.LsReq\x1a\f.sliverpb.Ls\x12$\n" +
	"\x02Cd\x12\x0f.sliverpb.CdReq\x1a\r.sliverpb.Pwd\x12&\n" +
	"\x03Pwd\x12\x10.sliverpb.PwdReq\x1a\r.sliverpb.Pwd\x12#\n" +
	"\x02Mv\x12\x0f.sliverpb.MvReq\x1a\f.sliverpb.Mv\x12#\n" +
	"\x02Cp\x12\x0f.sliverpb.CpReq\x1a\f.sliverpb.Cp\x12#\n" +
	"\x02Rm\x12\x0f.sliverpb.RmReq\x1a\f.sliverpb.Rm\x12,\n" +
	"\x05Mkdir\x12\x12.sliverpb.MkdirReq\x1a\x0f.sliverpb.Mkdir\x125\n" +
	"\bDownload\x12\x15.sliverpb.DownloadReq\x1a\x12.sliverpb.Download\x12/\n" +
	"\x06Upload\x12\x13.sliverpb.UploadReq\x1a\x10.sliverpb.Upload\x12)\n" +
	"\x04Grep\x12\x11.sliverpb.GrepReq\x1a\x0e.sliverpb.Grep\x12,\n" +
	"\x05Chmod\x12\x12.sliverpb.ChmodReq\x1a\x0f.sliverpb.Chmod\x12,\n" +
	"\x05Chown\x12\x12.sliverpb.ChownReq\x1a\x0f.sliverpb.Chown\x122\n" +
	"\aChtimes\x12\x14.sliverpb.ChtimesReq\x1a\x11.sliverpb.Chtimes\x127\n" +
	"\fMemfilesList\x12\x19.sliverpb.MemfilesListReq\x1a\f.sliverpb.Ls\x12>\n" +
	"\vMemfilesAdd\x12\x18.sliverpb.MemfilesAddReq\x1a\x15.sliverpb.MemfilesAdd\x12;\n" +
	"\n" +
	"MemfilesRm\x12\x17.sliverpb.MemfilesRmReq\x1a\x14.sliverpb.MemfilesRm\x12,\n" +
	"\x05Mount\x12\x12.sliverpb.MountReq\x1a\x0f.sliverpb.Mount\x12>\n" +
	"\vProcessDump\x12\x18.sliverpb.ProcessDumpReq\x1a\x15.sliverpb.ProcessDump\x12,\n" +
	"\x05RunAs\x12\x12.sliverpb.RunAsReq\x1a\x0f.sliverpb.RunAs\x12>\n" +
	"\vImpersonate\x12\x18.sliverpb.ImpersonateReq\x1a\x15.sliverpb.Impersonate\x128\n" +
	"\tRevToSelf\x12\x16.sliverpb.RevToSelfReq\x1a\x13.sliverpb.RevToSelf\x128\n" +
	"\tGetSystem\x12\x16.clientpb.GetSystemReq\x1a\x13.sliverpb.GetSystem\x12)\n" +
	"\x04Task\x12\x11.sliverpb.TaskReq\x1a\x0e.sliverpb.Task\x12'\n" +
	"\x03Msf\x12\x10.clientpb.MSFReq\x1a\x0e.sliverpb.Task\x123\n" +
	"\tMsfRemote\x12\x16.clientpb.MSFRemoteReq\x1a\x0e.sliverpb.Task\x12J\n" +
	"\x0fExecuteAssembly\x12\x1c.sliverpb.ExecuteAssemblyReq\x1a\x19.sliverpb.ExecuteAssembly\x122\n" +
	"\aMigrate\x12\x14.clientpb.MigrateReq\x1a\x11.sliverpb.Migrate\x122\n" +
	"\aExecute\x12\x14.sliverpb.ExecuteReq\x1a\x11.sliverpb.Execute\x12@\n" +
	"\x0eExecuteWindows\x12\x1b.sliverpb.ExecuteWindowsReq\x1a\x11.sliverpb.Execute\x125\n" +
	"\bSideload\x12\x15.sliverpb.SideloadReq\x1a\x12.sliverpb.Sideload\x12;\n" +
	"\bSpawnDll\x12\x1b.sliverpb.InvokeSpawnDllReq\x1a\x12.sliverpb.SpawnDll\x12;\n" +
	"\n" +
	"Screenshot\x12\x17.sliverpb.ScreenshotReq\x1a\x14.sliverpb.Screenshot\x12P\n" +
	"\x11CurrentTokenOwner\x12\x1e.sliverpb.CurrentTokenOwnerReq\x1a\x1b.sliverpb.CurrentTokenOwner\x125\n" +
	"\bServices\x12\x15.sliverpb.ServicesReq\x1a\x12.sliverpb.Services\x12D\n" +
	"\rServiceDetail\x12\x1a.sliverpb.ServiceDetailReq\x1a\x17.sliverpb.ServiceDetail\x12L\n" +
	"\x12StartServiceByName\x12\x1f.sliverpb.StartServiceByNameReq\x1a\x15.sliverpb.ServiceInfo\x12N\n" +
	"\x12PivotStartListener\x12\x1f.sliverpb.PivotStartListenerReq\x1a\x17.sliverpb.PivotListener\x12D\n" +
	"\x11PivotStopListener\x12\x1e.sliverpb.PivotStopListenerReq\x1a\x0f.commonpb.Empty\x12N\n" +
	"\x15PivotSessionListeners\x12\x1b.sliverpb.PivotListenersReq\x1a\x18.sliverpb.PivotListeners\x123\n" +
	"\n" +
	"PivotGraph\x12\x0f.commonpb.Empty\x1a\x14.clientpb.PivotGraph\x12@\n" +
	"\fStartService\x12\x19.sliverpb.StartServiceReq\x1a\x15.sliverpb.ServiceInfo\x12>\n" +
	"\vStopService\x12\x18.sliverpb.StopServiceReq\x1a\x15.sliverpb.ServiceInfo\x12B\n" +
	"\rRemoveService\x12\x1a.sliverpb.RemoveServiceReq\x1a\x15.sliverpb.ServiceInfo\x128\n" +
	"\tMakeToken\x12\x16.sliverpb.MakeTokenReq\x1a\x13.sliverpb.MakeToken\x12-\n" +
	"\x06GetEnv\x12\x10.sliverpb.EnvReq\x1a\x11.sliverpb.EnvInfo\x12/\n" +
	"\x06SetEnv\x12\x13.sliverpb.SetEnvReq\x1a\x10.sliverpb.SetEnv\x125\n" +
	"\bUnsetEnv\x12\x15.sliverpb.UnsetEnvReq\x1a\x12.sliverpb.UnsetEnv\x125\n" +
	"\bBackdoor\x12\x15.clientpb.BackdoorReq\x1a\x12.clientpb.Backdoor\x12A\n" +
	"\fRegistryRead\x12\x19.sliverpb.RegistryReadReq\x1a\x16.sliverpb.RegistryRead\x12D\n" +
	"\rRegistryWrite\x12\x1a.sliverpb.RegistryWriteReq\x1a\x17.sliverpb.RegistryWrite\x12P\n" +
	"\x11RegistryCreateKey\x12\x1e.sliverpb.RegistryCreateKeyReq\x1a\x1b.sliverpb.RegistryCreateKey\x12P\n" +
	"\x11RegistryDeleteKey\x12\x1e.sliverpb.RegistryDeleteKeyReq\x1a\x1b.sliverpb.RegistryDeleteKey\x12T\n" +
	"\x13RegistryListSubKeys\x12\x1f.sliverpb.RegistrySubKeyListReq\x1a\x1c.sliverpb.RegistrySubKeyList\x12S\n" +
	"\x12RegistryListValues\x12\x1f.sliverpb.RegistryListValuesReq\x1a\x1c.sliverpb.RegistryValuesList\x12M\n" +
	"\x10RegistryReadHive\x12\x1d.sliverpb.RegistryReadHiveReq\x1a\x1a.sliverpb.RegistryReadHive\x12>\n" +
	"\rRunSSHCommand\x12\x17.sliverpb.SSHCommandReq\x1a\x14.sliverpb.SSHCommand\x128\n" +
	"\tHijackDLL\x12\x16.clientpb.DllHijackReq\x1a\x13.clientpb.DllHijack\x125\n" +
	"\bGetPrivs\x12\x15.sliverpb.GetPrivsReq\x1a\x12.sliverpb.GetPrivs\x12W\n" +
	"\x15StartRportFwdListener\x12\".sliverpb.RportFwdStartListenerReq\x1a\x1a.sliverpb.RportFwdListener\x12S\n" +
	"\x14GetRportFwdListeners\x12\x1e.sliverpb.RportFwdListenersReq\x1a\x1b.sliverpb.RportFwdListeners\x12U\n" +
	"\x14StopRportFwdListener\x12!.sliverpb.RportFwdStopListenerReq\x1a\x1a.sliverpb.RportFwdListener\x12;\n" +
	"\vOpenSession\x12\x15.sliverpb.OpenSession\x1a\x15.sliverpb.OpenSession\x127\n" +
	"\fCloseSession\x12\x16.sliverpb.CloseSession\x1a\x0f.commonpb.Empty\x12P\n" +
	"\x11RegisterExtension\x12\x1e.sliverpb.RegisterExtensionReq\x1a\x1b.sliverpb.RegisterExtension\x12D\n" +
	"\rCallExtension\x12\x1a.sliverpb.CallExtensionReq\x1a\x17.sliverpb.CallExtension\x12G\n" +
	"\x0eListExtensions\x12\x1b.sliverpb.ListExtensionsReq\x1a\x18.sliverpb.ListExtensions\x12\\\n" +
	"\x15RegisterWasmExtension\x12\".sliverpb.RegisterWasmExtensionReq\x1a\x1f.sliverpb.RegisterWasmExtension\x12S\n" +
	"\x12ListWasmExtensions\x12\x1f.sliverpb.ListWasmExtensionsReq\x1a\x1c.sliverpb.ListWasmExtensions\x12P\n" +
	"\x11ExecWasmExtension\x12\x1e.sliverpb.ExecWasmExtensionReq\x1a\x1b.sliverpb.ExecWasmExtension\x12N\n" +
	"\x12WGStartPortForward\x12\x1f.sliverpb.WGPortForwardStartReq\x1a\x17.sliverpb.WGPortForward\x12L\n" +
	"\x11WGStopPortForward\x12\x1e.sliverpb.WGPortForwardStopReq\x1a\x17.sliverpb.WGPortForward\x12<\n" +
	"\fWGStartSocks\x12\x19.sliverpb.WGSocksStartReq\x1a\x11.sliverpb.WGSocks\x12:\n" +
	"\vWGStopSocks\x12\x18.sliverpb.WGSocksStopReq\x1a\x11.sliverpb.WGSocks\x12K\n" +
	"\x10WGListForwarders\x12\x1c.sliverpb.WGTCPForwardersReq\x1a\x19.sliverpb.WGTCPForwarders\x12K\n" +
	"\x12WGListSocksServers\x12\x1b.sliverpb.WGSocksServersReq\x1a\x18.sliverpb.WGSocksServers\x12,\n" +
	"\x05Shell\x12\x12.sliverpb.ShellReq\x1a\x0f.sliverpb.Shell\x122\n" +
	"\aPortfwd\x12\x14.sliverpb.PortfwdReq\x1a\x11.sliverpb.Portfwd\x12/\n" +
	"\vCreateSocks\x12\x0f.sliverpb.Socks\x1a\x0f.sliverpb.Socks\x12.\n" +
	"\n" +
	"CloseSocks\x12\x0f.sliverpb.Socks\x1a\x0f.commonpb.Empty\x12:\n" +
	"\n" +
	"SocksProxy\x12\x13.sliverpb.SocksData\x1a\x13.sliverpb.SocksData(\x010\x01\x122\n" +
	"\fCreateTunnel\x12\x10.sliverpb.Tunnel\x1a\x10.sliverpb.Tunnel\x120\n" +
	"\vCloseTunnel\x12\x10.sliverpb.Tunnel\x1a\x0f.commonpb.Empty\x12<\n" +
	"\n" +
	"TunnelData\x12\x14.sliverpb.TunnelData\x1a\x14.sliverpb.TunnelData(\x010\x01\x12,\n" +
	"\x06Events\x12\x0f.commonpb.Empty\x1a\x0f.clientpb.Event0\x01B,Z*github.com/bishopfox/sliver/protobuf/rpcpbb\x06proto3"

var file_rpcpb_services_proto_goTypes = []any{
	(*commonpb.Empty)(nil),                    // 0: commonpb.Empty
	(*clientpb.ClientLogData)(nil),            // 1: clientpb.ClientLogData
	(*sliverpb.KillReq)(nil),                  // 2: sliverpb.KillReq
	(*sliverpb.ReconfigureReq)(nil),           // 3: sliverpb.ReconfigureReq
	(*clientpb.RenameReq)(nil),                // 4: clientpb.RenameReq
	(*clientpb.MonitoringProvider)(nil),       // 5: clientpb.MonitoringProvider
	(*clientpb.MTLSListenerReq)(nil),          // 6: clientpb.MTLSListenerReq
	(*clientpb.WGListenerReq)(nil),            // 7: clientpb.WGListenerReq
	(*clientpb.DNSListenerReq)(nil),           // 8: clientpb.DNSListenerReq
	(*clientpb.HTTPListenerReq)(nil),          // 9: clientpb.HTTPListenerReq
	(*clientpb.Beacon)(nil),                   // 10: clientpb.Beacon
	(*clientpb.BeaconTask)(nil),               // 11: clientpb.BeaconTask
	(*clientpb.BeaconIntegrity)(nil),          // 12: clientpb.BeaconIntegrity
	(*clientpb.KillJobReq)(nil),               // 13: clientpb.KillJobReq
	(*clientpb.RestartJobReq)(nil),            // 14: clientpb.RestartJobReq
	(*clientpb.StagerListenerReq)(nil),        // 15: clientpb.StagerListenerReq
	(*clientpb.Loot)(nil),                     // 16: clientpb.Loot
	(*clientpb.Credentials)(nil),              // 17: clientpb.Credentials
	(*clientpb.Credential)(nil),               // 18: clientpb.Credential
	(*clientpb.Host)(nil),                     // 19: clientpb.Host
	(*clientpb.IOC)(nil),                      // 20: clientpb.IOC
	(*clientpb.HostScanReq)(nil),              // 21: clientpb.HostScanReq
	(*clientpb.GenerateReq)(nil),              // 22: clientpb.GenerateReq
	(*clientpb.ExternalGenerateReq)(nil),      // 23: clientpb.ExternalGenerateReq
	(*clientpb.ExternalImplantBinary)(nil),    // 24: clientpb.ExternalImplantBinary
	(*clientpb.ImplantBuild)(nil),             // 25: clientpb.ImplantBuild
	(*clientpb.GenerateStageReq)(nil),         // 26: clientpb.GenerateStageReq
	(*clientpb.ImplantStageReq)(nil),          // 27: clientpb.ImplantStageReq
	(*clientpb.C2ProfileReq)(nil),             // 28: clientpb.C2ProfileReq
	(*clientpb.HTTPC2ConfigReq)(nil),          // 29: clientpb.HTTPC2ConfigReq
	(*clientpb.Builder)(nil),                  // 30: clientpb.Builder
	(*clientpb.Event)(nil),                    // 31: clientpb.Event
	(*clientpb.CertificatesReq)(nil),          // 32: clientpb.CertificatesReq
	(*clientpb.Crackstation)(nil),             // 33: clientpb.Crackstation
	(*clientpb.CrackBenchmark)(nil),           // 34: clientpb.CrackBenchmark
	(*clientpb.CrackTask)(nil),                // 35: clientpb.CrackTask
	(*clientpb.CrackFile)(nil),                // 36: clientpb.CrackFile
	(*clientpb.CrackFileChunk)(nil),           // 37: clientpb.CrackFileChunk
	(*clientpb.RegenerateReq)(nil),            // 38: clientpb.RegenerateReq
	(*clientpb.DeleteReq)(nil),                // 39: clientpb.DeleteReq
	(*clientpb.ImplantProfile)(nil),           // 40: clientpb.ImplantProfile
	(*clientpb.ShellcodeRDIReq)(nil),          // 41: clientpb.ShellcodeRDIReq
	(*clientpb.ShellcodeEncodeReq)(nil),       // 42: clientpb.ShellcodeEncodeReq
	(*clientpb.TrafficEncoder)(nil),           // 43: clientpb.TrafficEncoder
	(*clientpb.Website)(nil),                  // 44: clientpb.Website
	(*clientpb.WebsiteAddContent)(nil),        // 45: clientpb.WebsiteAddContent
	(*clientpb.WebsiteRemoveContent)(nil),     // 46: clientpb.WebsiteRemoveContent
	(*sliverpb.Ping)(nil),                     // 47: sliverpb.Ping
	(*sliverpb.PsReq)(nil),                    // 48: sliverpb.PsReq
	(*sliverpb.TerminateReq)(nil),             // 49: sliverpb.TerminateReq
	(*sliverpb.IfconfigReq)(nil),              // 50: sliverpb.IfconfigReq
	(*sliverpb.NetstatReq)(nil),               // 51: sliverpb.NetstatReq
	(*sliverpb.LsReq)(nil),                    // 52: sliverpb.LsReq
	(*sliverpb.CdReq)(nil),                    // 53: sliverpb.CdReq
	(*sliverpb.PwdReq)(nil),                   // 54: sliverpb.PwdReq
	(*sliverpb.MvReq)(nil),                    // 55: sliverpb.MvReq
	(*sliverpb.CpReq)(nil),                    // 56: sliverpb.CpReq
	(*sliverpb.RmReq)(nil),                    // 57: sliverpb.RmReq
	(*sliverpb.MkdirReq)(nil),                 // 58: sliverpb.MkdirReq
	(*sliverpb.DownloadReq)(nil),              // 59: sliverpb.DownloadReq
	(*sliverpb.UploadReq)(nil),                // 60: sliverpb.UploadReq
	(*sliverpb.GrepReq)(nil),                  // 61: sliverpb.GrepReq
	(*sliverpb.ChmodReq)(nil),                 // 62: sliverpb.ChmodReq
	(*sliverpb.ChownReq)(nil),                 // 63: sliverpb.ChownReq
	(*sliverpb.ChtimesReq)(nil),               // 64: sliverpb.ChtimesReq
	(*sliverpb.MemfilesListReq)(nil),          // 65: sliverpb.MemfilesListReq
	(*sliverpb.MemfilesAddReq)(nil),           // 66: sliverpb.MemfilesAddReq
	(*sliverpb.MemfilesRmReq)(nil),            // 67: sliverpb.MemfilesRmReq
	(*sliverpb.MountReq)(nil),                 // 68: sliverpb.MountReq
	(*sliverpb.ProcessDumpReq)(nil),           // 69: sliverpb.ProcessDumpReq
	(*sliverpb.RunAsReq)(nil),                 // 70: sliverpb.RunAsReq
	(*sliverpb.ImpersonateReq)(nil),           // 71: sliverpb.ImpersonateReq
	(*sliverpb.RevToSelfReq)(nil),             // 72: sliverpb.RevToSelfReq
	(*clientpb.GetSystemReq)(nil),             // 73: clientpb.GetSystemReq
	(*sliverpb.TaskReq)(nil),                  // 74: sliverpb.TaskReq
	(*clientpb.MSFReq)(nil),                   // 75: clientpb.MSFReq
	(*clientpb.MSFRemoteReq)(nil),             // 76: clientpb.MSFRemoteReq
	(*sliverpb.ExecuteAssemblyReq)(nil),       // 77: sliverpb.ExecuteAssemblyReq
	(*clientpb.MigrateReq)(nil),               // 78: clientpb.MigrateReq
	(*sliverpb.ExecuteReq)(nil),               // 79: sliverpb.ExecuteReq
	(*sliverpb.ExecuteWindowsReq)(nil),        // 80: sliverpb.ExecuteWindowsReq
	(*sliverpb.SideloadReq)(nil),              // 81: sliverpb.SideloadReq
	(*sliverpb.InvokeSpawnDllReq)(nil),        // 82: sliverpb.InvokeSpawnDllReq
	(*sliverpb.ScreenshotReq)(nil),            // 83: sliverpb.ScreenshotReq
	(*sliverpb.CurrentTokenOwnerReq)(nil),     // 84: sliverpb.CurrentTokenOwnerReq
	(*sliverpb.ServicesReq)(nil),              // 85: sliverpb.ServicesReq
	(*sliverpb.ServiceDetailReq)(nil),         // 86: sliverpb.ServiceDetailReq
	(*sliverpb.StartServiceByNameReq)(nil),    // 87: sliverpb.StartServiceByNameReq
	(*sliverpb.PivotStartListenerReq)(nil),    // 88: sliverpb.PivotStartListenerReq
	(*sliverpb.PivotStopListenerReq)(nil),     // 89: sliverpb.PivotStopListenerReq
	(*sliverpb.PivotListenersReq)(nil),        // 90: sliverpb.PivotListenersReq
	(*sliverpb.StartServiceReq)(nil),          // 91: sliverpb.StartServiceReq
	(*sliverpb.StopServiceReq)(nil),           // 92: sliverpb.StopServiceReq
	(*sliverpb.RemoveServiceReq)(nil),         // 93: sliverpb.RemoveServiceReq
	(*sliverpb.MakeTokenReq)(nil),             // 94: sliverpb.MakeTokenReq
	(*sliverpb.EnvReq)(nil),                   // 95: sliverpb.EnvReq
	(*sliverpb.SetEnvReq)(nil),                // 96: sliverpb.SetEnvReq
	(*sliverpb.UnsetEnvReq)(nil),              // 97: sliverpb.UnsetEnvReq
	(*clientpb.BackdoorReq)(nil),              // 98: clientpb.BackdoorReq
	(*sliverpb.RegistryReadReq)(nil),          // 99: sliverpb.RegistryReadReq
	(*sliverpb.RegistryWriteReq)(nil),         // 100: sliverpb.RegistryWriteReq
	(*sliverpb.RegistryCreateKeyReq)(nil),     // 101: sliverpb.RegistryCreateKeyReq
	(*sliverpb.RegistryDeleteKeyReq)(nil),     // 102: sliverpb.RegistryDeleteKeyReq
	(*sliverpb.RegistrySubKeyListReq)(nil),    // 103: sliverpb.RegistrySubKeyListReq
	(*sliverpb.RegistryListValuesReq)(nil),    // 104: sliverpb.RegistryListValuesReq
	(*sliverpb.RegistryReadHiveReq)(nil),      // 105: sliverpb.RegistryReadHiveReq
	(*sliverpb.SSHCommandReq)(nil),            // 106: sliverpb.SSHCommandReq
	(*clientpb.DllHijackReq)(nil),             // 107: clientpb.DllHijackReq
	(*sliverpb.GetPrivsReq)(nil),              // 108: sliverpb.GetPrivsReq
	(*sliverpb.RportFwdStartListenerReq)(nil), // 109: sliverpb.RportFwdStartListenerReq
	(*sliverpb.RportFwdListenersReq)(nil),     // 110: sliverpb.RportFwdListenersReq
	(*sliverpb.RportFwdStopListenerReq)(nil),  // 111: sliverpb.RportFwdStopListenerReq
	(*sliverpb.OpenSession)(nil),              // 112: sliverpb.OpenSession
	(*sliverpb.CloseSession)(nil),             // 113: sliverpb.CloseSession
	(*sliverpb.RegisterExtensionReq)(nil),     // 114: sliverpb.RegisterExtensionReq
	(*sliverpb.CallExtensionReq)(nil),         // 115: sliverpb.CallExtensionReq
	(*sliverpb.ListExtensionsReq)(nil),        // 116: sliverpb.ListExtensionsReq
	(*sliverpb.RegisterWasmExtensionReq)(nil), // 117: sliverpb.RegisterWasmExtensionReq
	(*sliverpb.ListWasmExtensionsReq)(nil),    // 118: sliverpb.ListWasmExtensionsReq
	(*sliverpb.ExecWasmExtensionReq)(nil),     // 119: sliverpb.ExecWasmExtensionReq
	(*sliverpb.WGPortForwardStartReq)(nil),    // 120: sliverpb.WGPortForwardStartReq
	(*sliverpb.WGPortForwardStopReq)(nil),     // 121: sliverpb.WGPortForwardStopReq
	(*sliverpb.WGSocksStartReq)(nil),          // 122: sliverpb.WGSocksStartReq
	(*sliverpb.WGSocksStopReq)(nil),           // 123: sliverpb.WGSocksStopReq
	(*sliverpb.WGTCPForwardersReq)(nil),       // 124: sliverpb.WGTCPForwardersReq
	(*sliverpb.WGSocksServersReq)(nil),        // 125: sliverpb.WGSocksServersReq
	(*sliverpb.ShellReq)(nil),                 // 126: sliverpb.ShellReq
	(*sliverpb.PortfwdReq)(nil),               // 127: sliverpb.PortfwdReq
	(*sliverpb.Socks)(nil),                    // 128: sliverpb.Socks
	(*sliverpb.SocksData)(nil),                // 129: sliverpb.SocksData
	(*sliverpb.Tunnel)(nil),                   // 130: sliverpb.Tunnel
	(*sliverpb.TunnelData)(nil),               // 131: sliverpb.TunnelData
	(*clientpb.Version)(nil),                  // 132: clientpb.Version
	(*clientpb.Operators)(nil),                // 133: clientpb.Operators
	(*sliverpb.Reconfigure)(nil),              // 134: sliverpb.Reconfigure
	(*clientpb.Sessions)(nil),                 // 135: clientpb.Sessions
	(*commonpb.Response)(nil),                 // 136: commonpb.Response
	(*clientpb.MonitoringProviders)(nil),      // 137: clientpb.MonitoringProviders
	(*clientpb.ListenerJob)(nil),              // 138: clientpb.ListenerJob
	(*clientpb.Beacons)(nil),                  // 139: clientpb.Beacons
	(*clientpb.BeaconTasks)(nil),              // 140: clientpb.BeaconTasks
	(*clientpb.Jobs)(nil),                     // 141: clientpb.Jobs
	(*clientpb.KillJob)(nil),                  // 142: clientpb.KillJob
	(*clientpb.StagerListener)(nil),           // 143: clientpb.StagerListener
	(*clientpb.AllLoot)(nil),                  // 144: clientpb.AllLoot
	(*clientpb.AllHosts)(nil),                 // 145: clientpb.AllHosts
	(*clientpb.HostScanResults)(nil),          // 146: clientpb.HostScanResults
	(*clientpb.Generate)(nil),                 // 147: clientpb.Generate
	(*clientpb.ExternalImplantConfig)(nil),    // 148: clientpb.ExternalImplantConfig
	(*clientpb.HTTPC2Configs)(nil),            // 149: clientpb.HTTPC2Configs
	(*clientpb.HTTPC2Config)(nil),             // 150: clientpb.HTTPC2Config
	(*clientpb.Builders)(nil),                 // 151: clientpb.Builders
	(*clientpb.CertificateInfo)(nil),          // 152: clientpb.CertificateInfo
	(*clientpb.Crackstations)(nil),            // 153: clientpb.Crackstations
	(*clientpb.CrackFiles)(nil),               // 154: clientpb.CrackFiles
	(*clientpb.ImplantBuilds)(nil),            // 155: clientpb.ImplantBuilds
	(*clientpb.Canaries)(nil),                 // 156: clientpb.Canaries
	(*clientpb.WGClientConfig)(nil),           // 157: clientpb.WGClientConfig
	(*clientpb.UniqueWGIP)(nil),               // 158: clientpb.UniqueWGIP
	(*clientpb.ImplantProfiles)(nil),          // 159: clientpb.ImplantProfiles
	(*clientpb.ShellcodeRDI)(nil),             // 160: clientpb.ShellcodeRDI
	(*clientpb.Compiler)(nil),                 // 161: clientpb.Compiler
	(*clientpb.ShellcodeEncode)(nil),          // 162: clientpb.ShellcodeEncode
	(*clientpb.ShellcodeEncoderMap)(nil),      // 163: clientpb.ShellcodeEncoderMap
	(*clientpb.TrafficEncoderMap)(nil),        // 164: clientpb.TrafficEncoderMap
	(*clientpb.TrafficEncoderTests)(nil),      // 165: clientpb.TrafficEncoderTests
	(*clientpb.Websites)(nil),                 // 166: clientpb.Websites
	(*sliverpb.Ps)(nil),                       // 167: sliverpb.Ps
	(*sliverpb.Terminate)(nil),                // 168: sliverpb.Terminate
	(*sliverpb.Ifconfig)(nil),                 // 169: sliverpb.Ifconfig
	(*sliverpb.Netstat)(nil),                  // 170: sliverpb.Netstat
	(*sliverpb.Ls)(nil),                       // 171: sliverpb.Ls
	(*sliverpb.Pwd)(nil),                      // 172: sliverpb.Pwd
	(*sliverpb.Mv)(nil),                       // 173: sliverpb.Mv
	(*sliverpb.Cp)(nil),                       // 174: sliverpb.Cp
	(*sliverpb.Rm)(nil),                       // 175: sliverpb.Rm
	(*sliverpb.Mkdir)(nil),                    // 176: sliverpb.Mkdir
	(*sliverpb.Download)(nil),                 // 177: sliverpb.Download
	(*sliverpb.Upload)(nil),                   // 178: sliverpb.Upload
	(*sliverpb.Grep)(nil),                     // 179: sliverpb.Grep
	(*sliverpb.Chmod)(nil),                    // 180: sliverpb.Chmod
	(*sliverpb.Chown)(nil),                    // 181: sliverpb.Chown
	(*sliverpb.Chtimes)(nil),                  // 182: sliverpb.Chtimes
	(*sliverpb.MemfilesAdd)(nil),              // 183: sliverpb.MemfilesAdd
	(*sliverpb.MemfilesRm)(nil),               // 184: sliverpb.MemfilesRm
	(*sliverpb.Mount)(nil),                    // 185: sliverpb.Mount
	(*sliverpb.ProcessDump)(nil),              // 186: sliverpb.ProcessDump
	(*sliverpb.RunAs)(nil),                    // 187: sliverpb.RunAs
	(*sliverpb.Impersonate)(nil),              // 188: sliverpb.Impersonate
	(*sliverpb.RevToSelf)(nil),                // 189: sliverpb.RevToSelf
	(*sliverpb.GetSystem)(nil),                // 190: sliverpb.GetSystem
	(*sliverpb.Task)(nil),                     // 191: sliverpb.Task
	(*sliverpb.ExecuteAssembly)(nil),          // 192: sliverpb.ExecuteAssembly
	(*sliverpb.Migrate)(nil),                  // 193: sliverpb.Migrate
	(*sliverpb.Execute)(nil),                  // 194: sliverpb.Execute
	(*sliverpb.Sideload)(nil),                 // 195: sliverpb.Sideload
	(*sliverpb.SpawnDll)(nil),                 // 196: sliverpb.SpawnDll
	(*sliverpb.Screenshot)(nil),               // 197: sliverpb.Screenshot
	(*sliverpb.CurrentTokenOwner)(nil),        // 198: sliverpb.CurrentTokenOwner
	(*sliverpb.Services)(nil),                 // 199: sliverpb.Services
	(*sliverpb.ServiceDetail)(nil),            // 200: sliverpb.ServiceDetail
	(*sliverpb.ServiceInfo)(nil),              // 201: sliverpb.ServiceInfo
	(*sliverpb.PivotListener)(nil),            // 202: sliverpb.PivotListener
	(*sliverpb.PivotListeners)(nil),           // 203: sliverpb.PivotListeners
	(*clientpb.PivotGraph)(nil),               // 204: clientpb.PivotGraph
	(*sliverpb.MakeToken)(nil),                // 205: sliverpb.MakeToken
	(*sliverpb.EnvInfo)(nil),                  // 206: sliverpb.EnvInfo
	(*sliverpb.SetEnv)(nil),                   // 207: sliverpb.SetEnv
	(*sliverpb.UnsetEnv)(nil),                 // 208: sliverpb.UnsetEnv
	(*clientpb.Backdoor)(nil),                 // 209: clientpb.Backdoor
	(*sliverpb.RegistryRead)(nil),             // 210: sliverpb.RegistryRead
	(*sliverpb.RegistryWrite)(nil),            // 211: sliverpb.RegistryWrite
	(*sliverpb.RegistryCreateKey)(nil),        // 212: sliverpb.RegistryCreateKey
	(*sliverpb.RegistryDeleteKey)(nil),        // 213: sliverpb.RegistryDeleteKey
	(*sliverpb.RegistrySubKeyList)(nil),       // 214: sliverpb.RegistrySubKeyList
	(*sliverpb.RegistryValuesList)(nil),       // 215: sliverpb.RegistryValuesList
	(*sliverpb.RegistryReadHive)(nil),         // 216: sliverpb.RegistryReadHive
	(*sliverpb.SSHCommand)(nil),               // 217: sliverpb.SSHCommand
	(*clientpb.DllHijack)(nil),                // 218: clientpb.DllHijack
	(*sliverpb.GetPrivs)(nil),                 // 219: sliverpb.GetPrivs
	(*sliverpb.RportFwdListener)(nil),         // 220: sliverpb.RportFwdListener
	(*sliverpb.RportFwdListeners)(nil),        // 221: sliverpb.RportFwdListeners
	(*sliverpb.RegisterExtension)(nil),        // 222: sliverpb.RegisterExtension
	(*sliverpb.CallExtension)(nil),            // 223: sliverpb.CallExtension
	(*sliverpb.ListExtensions)(nil),           // 224: sliverpb.ListExtensions
	(*sliverpb.RegisterWasmExtension)(nil),    // 225: sliverpb.RegisterWasmExtension
	(*sliverpb.ListWasmExtensions)(nil),       // 226: sliverpb.ListWasmExtensions
	(*sliverpb.ExecWasmExtension)(nil),        // 227: sliverpb.ExecWasmExtension
	(*sliverpb.WGPortForward)(nil),            // 228: sliverpb.WGPortForward
	(*sliverpb.WGSocks)(nil),                  // 229: sliverpb.WGSocks
	(*sliverpb.WGTCPForwarders)(nil),          // 230: sliverpb.WGTCPForwarders
	(*sliverpb.WGSocksServers)(nil),           // 231: sliverpb.WGSocksServers
	(*sliverpb.Shell)(nil),                    // 232: sliverpb.Shell
	(*sliverpb.Portfwd)(nil),                  // 233: sliverpb.Portfwd
}
var file_rpcpb_services_proto_depIdxs = []int32{
	0,   // 0: rpcpb.SliverRPC.GetVersion:input_type -> commonpb.Empty
	1,   // 1: rpcpb.SliverRPC.ClientLog:input_type -> clientpb.ClientLogData
	0,   // 2: rpcpb.SliverRPC.GetOperators:input_type -> commonpb.Empty
	2,   // 3: rpcpb.SliverRPC.Kill:input_type -> sliverpb.KillReq
	3,   // 4: rpcpb.SliverRPC.Reconfigure:input_type -> sliverpb.ReconfigureReq
	4,   // 5: rpcpb.SliverRPC.Rename:input_type -> clientpb.RenameReq
	0,   // 6: rpcpb.SliverRPC.GetSessions:input_type -> commonpb.Empty
	0,   // 7: rpcpb.SliverRPC.MonitorStart:input_type -> commonpb.Empty
	0,   // 8: rpcpb.SliverRPC.MonitorStop:input_type -> commonpb.Empty
	0,   // 9: rpcpb.SliverRPC.MonitorListConfig:input_type -> commonpb.Empty
	5,   // 10: rpcpb.SliverRPC.MonitorAddConfig:input_type -> clientpb.MonitoringProvider
	5,   // 11: rpcpb.SliverRPC.MonitorDelConfig:input_type -> clientpb.MonitoringProvider
	6,   // 12: rpcpb.SliverRPC.StartMTLSListener:input_type -> clientpb.MTLSListenerReq
	7,   // 13: rpcpb.SliverRPC.StartWGListener:input_type -> clientpb.WGListenerReq
	8,   // 14: rpcpb.SliverRPC.StartDNSListener:input_type -> clientpb.DNSListenerReq
	9,   // 15: rpcpb.SliverRPC.StartHTTPSListener:input_type -> clientpb.HTTPListenerReq
	9,   // 16: rpcpb.SliverRPC.StartHTTPListener:input_type -> clientpb.HTTPListenerReq
	0,   // 17: rpcpb.SliverRPC.GetBeacons:input_type -> commonpb.Empty
	10,  // 18: rpcpb.SliverRPC.GetBeacon:input_type -> clientpb.Beacon
	10,  // 19: rpcpb.SliverRPC.RmBeacon:input_type -> clientpb.Beacon
	10,  // 20: rpcpb.SliverRPC.GetBeaconTasks:input_type -> clientpb.Beacon
	11,  // 21: rpcpb.SliverRPC.GetBeaconTaskContent:input_type -> clientpb.BeaconTask
	11,  // 22: rpcpb.SliverRPC.CancelBeaconTask:input_type -> clientpb.BeaconTask
	12,  // 23: rpcpb.SliverRPC.UpdateBeaconIntegrityInformation:input_type -> clientpb.BeaconIntegrity
	0,   // 24: rpcpb.SliverRPC.GetJobs:input_type -> commonpb.Empty
	13,  // 25: rpcpb.SliverRPC.KillJob:input_type -> clientpb.KillJobReq
	14,  // 26: rpcpb.SliverRPC.RestartJobs:input_type -> clientpb.RestartJobReq
	15,  // 27: rpcpb.SliverRPC.StartTCPStagerListener:input_type -> clientpb.StagerListenerReq
	16,  // 28: rpcpb.SliverRPC.LootAdd:input_type -> clientpb.Loot
	16,  // 29: rpcpb.SliverRPC.LootRm:input_type -> clientpb.Loot
	16,  // 30: rpcpb.SliverRPC.LootUpdate:input_type -> clientpb.Loot
	16,  // 31: rpcpb.SliverRPC.LootContent:input_type -> clientpb.Loot
	0,   // 32: rpcpb.SliverRPC.LootAll:input_type -> commonpb.Empty
	0,   // 33: rpcpb.SliverRPC.Creds:input_type -> commonpb.Empty
	17,  // 34: rpcpb.SliverRPC.CredsAdd:input_type -> clientpb.Credentials
	17,  // 35: rpcpb.SliverRPC.CredsRm:input_type -> clientpb.Credentials
	17,  // 36: rpcpb.SliverRPC.CredsUpdate:input_type -> clientpb.Credentials
	18,  // 37: rpcpb.SliverRPC.GetCredByID:input_type -> clientpb.Credential
	18,  // 38: rpcpb.SliverRPC.GetCredsByHashType:input_type -> clientpb.Credential
	18,  // 39: rpcpb.SliverRPC.GetPlaintextCredsByHashType:input_type -> clientpb.Credential
	18,  // 40: rpcpb.SliverRPC.CredsSniffHashType:input_type -> clientpb.Credential
	0,   // 41: rpcpb.SliverRPC.Hosts:input_type -> commonpb.Empty
	19,  // 42: rpcpb.SliverRPC.Host:input_type -> clientpb.Host
	19,  // 43: rpcpb.SliverRPC.HostRm:input_type -> clientpb.Host
	20,  // 44: rpcpb.SliverRPC.HostIOCRm:input_type -> clientpb.IOC
	21,  // 45: rpcpb.SliverRPC.HostScan:input_type -> clientpb.HostScanReq
	22,  // 46: rpcpb.SliverRPC.Generate:input_type -> clientpb.GenerateReq
	23,  // 47: rpcpb.SliverRPC.GenerateExternal:input_type -> clientpb.ExternalGenerateReq
	24,  // 48: rpcpb.SliverRPC.GenerateExternalSaveBuild:input_type -> clientpb.ExternalImplantBinary
	25,  // 49: rpcpb.SliverRPC.GenerateExternalGetBuildConfig:input_type -> clientpb.ImplantBuild
	26,  // 50: rpcpb.SliverRPC.GenerateStage:input_type -> clientpb.GenerateStageReq
	27,  // 51: rpcpb.SliverRPC.StageImplantBuild:input_type -> clientpb.ImplantStageReq
	0,   // 52: rpcpb.SliverRPC.GetHTTPC2Profiles:input_type -> commonpb.Empty
	28,  // 53: rpcpb.SliverRPC.GetHTTPC2ProfileByName:input_type -> clientpb.C2ProfileReq
	29,  // 54: rpcpb.SliverRPC.SaveHTTPC2Profile:input_type -> clientpb.HTTPC2ConfigReq
	30,  // 55: rpcpb.SliverRPC.BuilderRegister:input_type -> clientpb.Builder
	31,  // 56: rpcpb.SliverRPC.BuilderTrigger:input_type -> clientpb.Event
	0,   // 57: rpcpb.SliverRPC.Builders:input_type -> commonpb.Empty
	32,  // 58: rpcpb.SliverRPC.GetCertificateInfo:input_type -> clientpb.CertificatesReq
	33,  // 59: rpcpb.SliverRPC.CrackstationRegister:input_type -> clientpb.Crackstation
	31,  // 60: rpcpb.SliverRPC.CrackstationTrigger:input_type -> clientpb.Event
	34,  // 61: rpcpb.SliverRPC.CrackstationBenchmark:input_type -> clientpb.CrackBenchmark
	0,   // 62: rpcpb.SliverRPC.Crackstations:input_type -> commonpb.Empty
	35,  // 63: rpcpb.SliverRPC.CrackTaskByID:input_type -> clientpb.CrackTask
	35,  // 64: rpcpb.SliverRPC.CrackTaskUpdate:input_type -> clientpb.CrackTask
	36,  // 65: rpcpb.SliverRPC.CrackFilesList:input_type -> clientpb.CrackFile
	36,  // 66: rpcpb.SliverRPC.CrackFileCreate:input_type -> clientpb.CrackFile
	37,  // 67: rpcpb.SliverRPC.CrackFileChunkUpload:input_type -> clientpb.CrackFileChunk
	37,  // 68: rpcpb.SliverRPC.CrackFileChunkDownload:input_type -> clientpb.CrackFileChunk
	36,  // 69: rpcpb.SliverRPC.CrackFileComplete:input_type -> clientpb.CrackFile
	36,  // 70: rpcpb.SliverRPC.CrackFileDelete:input_type -> clientpb.CrackFile
	38,  // 71: rpcpb.SliverRPC.Regenerate:input_type -> clientpb.RegenerateReq
	0,   // 72: rpcpb.SliverRPC.ImplantBuilds:input_type -> commonpb.Empty
	39,  // 73: rpcpb.SliverRPC.DeleteImplantBuild:input_type -> clientpb.DeleteReq
	0,   // 74: rpcpb.SliverRPC.Canaries:input_type -> commonpb.Empty
	0,   // 75: rpcpb.SliverRPC.GenerateWGClientConfig:input_type -> commonpb.Empty
	0,   // 76: rpcpb.SliverRPC.GenerateUniqueIP:input_type -> commonpb.Empty
	0,   // 77: rpcpb.SliverRPC.ImplantProfiles:input_type -> commonpb.Empty
	39,  // 78: rpcpb.SliverRPC.DeleteImplantProfile:input_type -> clientpb.DeleteReq
	40,  // 79: rpcpb.SliverRPC.SaveImplantProfile:input_type -> clientpb.ImplantProfile
	41,  // 80: rpcpb.SliverRPC.ShellcodeRDI:input_type -> clientpb.ShellcodeRDIReq
	0,   // 81: rpcpb.SliverRPC.GetCompiler:input_type -> commonpb.Empty
	42,  // 82: rpcpb.SliverRPC.ShellcodeEncoder:input_type -> clientpb.ShellcodeEncodeReq
	0,   // 83: rpcpb.SliverRPC.ShellcodeEncoderMap:input_type -> commonpb.Empty
	0,   // 84: rpcpb.SliverRPC.TrafficEncoderMap:input_type -> commonpb.Empty
	43,  // 85: rpcpb.SliverRPC.TrafficEncoderAdd:input_type -> clientpb.TrafficEncoder
	43,  // 86: rpcpb.SliverRPC.TrafficEncoderRm:input_type -> clientpb.TrafficEncoder
	0,   // 87: rpcpb.SliverRPC.Websites:input_type -> commonpb.Empty
	44,  // 88: rpcpb.SliverRPC.Website:input_type -> clientpb.Website
	44,  // 89: rpcpb.SliverRPC.WebsiteRemove:input_type -> clientpb.Website
	45,  // 90: rpcpb.SliverRPC.WebsiteAddContent:input_type -> clientpb.WebsiteAddContent
	45,  // 91: rpcpb.SliverRPC.WebsiteUpdateContent:input_type -> clientpb.WebsiteAddContent
	46,  // 92: rpcpb.SliverRPC.WebsiteRemoveContent:input_type -> clientpb.WebsiteRemoveContent
	47,  // 93: rpcpb.SliverRPC.Ping:input_type -> sliverpb.Ping
	48,  // 94: rpcpb.SliverRPC.Ps:input_type -> sliverpb.PsReq
	49,  // 95: rpcpb.SliverRPC.Terminate:input_type -> sliverpb.TerminateReq
	50,  // 96: rpcpb.SliverRPC.Ifconfig:input_type -> sliverpb.IfconfigReq
	51,  // 97: rpcpb.SliverRPC.Netstat:input_type -> sliverpb.NetstatReq
	52,  // 98: rpcpb.SliverRPC.Ls:input_type -> sliverpb.LsReq
	53,  // 99: rpcpb.SliverRPC.Cd:input_type -> sliverpb.CdReq
	54,  // 100: rpcpb.SliverRPC.Pwd:input_type -> sliverpb.PwdReq
	55,  // 101: rpcpb.SliverRPC.Mv:input_type -> sliverpb.MvReq
	56,  // 102: rpcpb.SliverRPC.Cp:input_type -> sliverpb.CpReq
	57,  // 103: rpcpb.SliverRPC.Rm:input_type -> sliverpb.RmReq
	58,  // 104: rpcpb.SliverRPC.Mkdir:input_type -> sliverpb.MkdirReq
	59,  // 105: rpcpb.SliverRPC.Download:input_type -> sliverpb.DownloadReq
	60,  // 106: rpcpb.SliverRPC.Upload:input_type -> sliverpb.UploadReq
	61,  // 107: rpcpb.SliverRPC.Grep:input_type -> sliverpb.GrepReq
	62,  // 108: rpcpb.SliverRPC.Chmod:input_type -> sliverpb.ChmodReq
	63,  // 109: rpcpb.SliverRPC.Chown:input_type -> sliverpb.ChownReq
	64,  // 110: rpcpb.SliverRPC.Chtimes:input_type -> sliverpb.ChtimesReq
	65,  // 111: rpcpb.SliverRPC.MemfilesList:input_type -> sliverpb.MemfilesListReq
	66,  // 112: rpcpb.SliverRPC.MemfilesAdd:input_type -> sliverpb.MemfilesAddReq
	67,  // 113: rpcpb.SliverRPC.MemfilesRm:input_type -> sliverpb.MemfilesRmReq
	68,  // 114: rpcpb.SliverRPC.Mount:input_type -> sliverpb.MountReq
	69,  // 115: rpcpb.SliverRPC.ProcessDump:input_type -> sliverpb.ProcessDumpReq
	70,  // 116: rpcpb.SliverRPC.RunAs:input_type -> sliverpb.RunAsReq
	71,  // 117: rpcpb.SliverRPC.Impersonate:input_type -> sliverpb.ImpersonateReq
	72,  // 118: rpcpb.SliverRPC.RevToSelf:input_type -> sliverpb.RevToSelfReq
	73,  // 119: rpcpb.SliverRPC.GetSystem:input_type -> clientpb.GetSystemReq
	74,  // 120: rpcpb.SliverRPC.Task:input_type -> sliverpb.TaskReq
	75,  // 121: rpcpb.SliverRPC.Msf:input_type -> clientpb.MSFReq
	76,  // 122: rpcpb.SliverRPC.MsfRemote:input_type -> clientpb.MSFRemoteReq
	77,  // 123: rpcpb.SliverRPC.ExecuteAssembly:input_type -> sliverpb.ExecuteAssemblyReq
	78,  // 124: rpcpb.SliverRPC.Migrate:input_type -> clientpb.MigrateReq
	79,  // 125: rpcpb.SliverRPC.Execute:input_type -> sliverpb.ExecuteReq
	80,  // 126: rpcpb.SliverRPC.ExecuteWindows:input_type -> sliverpb.ExecuteWindowsReq
	81,  // 127: rpcpb.SliverRPC.Sideload:input_type -> sliverpb.SideloadReq
	82,  // 128: rpcpb.SliverRPC.SpawnDll:input_type -> sliverpb.InvokeSpawnDllReq
	83,  // 129: rpcpb.SliverRPC.Screenshot:input_type -> sliverpb.ScreenshotReq
	84,  // 130: rpcpb.SliverRPC.CurrentTokenOwner:input_type -> sliverpb.CurrentTokenOwnerReq
	85,  // 131: rpcpb.SliverRPC.Services:input_type -> sliverpb.ServicesReq
	86,  // 132: rpcpb.SliverRPC.ServiceDetail:input_type -> sliverpb.ServiceDetailReq
	87,  // 133: rpcpb.SliverRPC.StartServiceByName:input_type -> sliverpb.StartServiceByNameReq
	88,  // 134: rpcpb.SliverRPC.PivotStartListener:input_type -> sliverpb.PivotStartListenerReq
	89,  // 135: rpcpb.SliverRPC.PivotStopListener:input_type -> sliverpb.PivotStopListenerReq
	90,  // 136: rpcpb.SliverRPC.PivotSessionListeners:input_type -> sliverpb.PivotListenersReq
	0,   // 137: rpcpb.SliverRPC.PivotGraph:input_type -> commonpb.Empty
	91,  // 138: rpcpb.SliverRPC.StartService:input_type -> sliverpb.StartServiceReq
	92,  // 139: rpcpb.SliverRPC.StopService:input_type -> sliverpb.StopServiceReq
	93,  // 140: rpcpb.SliverRPC.RemoveService:input_type -> sliverpb.RemoveServiceReq
	94,  // 141: rpcpb.SliverRPC.MakeToken:input_type -> sliverpb.MakeTokenReq
	95,  // 142: rpcpb.SliverRPC.GetEnv:input_type -> sliverpb.EnvReq
	96,  // 143: rpcpb.SliverRPC.SetEnv:input_type -> sliverpb.SetEnvReq
	97,  // 144: rpcpb.SliverRPC.UnsetEnv:input_type -> sliverpb.UnsetEnvReq
	98,  // 145: rpcpb.SliverRPC.Backdoor:input_type -> clientpb.BackdoorReq
	99,  // 146: rpcpb.SliverRPC.RegistryRead:input_type -> sliverpb.RegistryReadReq
	100, // 147: rpcpb.SliverRPC.RegistryWrite:input_type -> sliverpb.RegistryWriteReq
	101, // 148: rpcpb.SliverRPC.RegistryCreateKey:input_type -> sliverpb.RegistryCreateKeyReq
	102, // 149: rpcpb.SliverRPC.RegistryDeleteKey:input_type -> sliverpb.RegistryDeleteKeyReq
	103, // 150: rpcpb.SliverRPC.RegistryListSubKeys:input_type -> sliverpb.RegistrySubKeyListReq
	104, // 151: rpcpb.SliverRPC.RegistryListValues:input_type -> sliverpb.RegistryListValuesReq
	105, // 152: rpcpb.SliverRPC.RegistryReadHive:input_type -> sliverpb.RegistryReadHiveReq
	106, // 153: rpcpb.SliverRPC.RunSSHCommand:input_type -> sliverpb.SSHCommandReq
	107, // 154: rpcpb.SliverRPC.HijackDLL:input_type -> clientpb.DllHijackReq
	108, // 155: rpcpb.SliverRPC.GetPrivs:input_type -> sliverpb.GetPrivsReq
	109, // 156: rpcpb.SliverRPC.StartRportFwdListener:input_type -> sliverpb.RportFwdStartListenerReq
	110, // 157: rpcpb.SliverRPC.GetRportFwdListeners:input_type -> sliverpb.RportFwdListenersReq
	111, // 158: rpcpb.SliverRPC.StopRportFwdListener:input_type -> sliverpb.RportFwdStopListenerReq
	112, // 159: rpcpb.SliverRPC.OpenSession:input_type -> sliverpb.OpenSession
	113, // 160: rpcpb.SliverRPC.CloseSession:input_type -> sliverpb.CloseSession
	114, // 161: rpcpb.SliverRPC.RegisterExtension:input_type -> sliverpb.RegisterExtensionReq
	115, // 162: rpcpb.SliverRPC.CallExtension:input_type -> sliverpb.CallExtensionReq
	116, // 163: rpcpb.SliverRPC.ListExtensions:input_type -> sliverpb.ListExtensionsReq
	117, // 164: rpcpb.SliverRPC.RegisterWasmExtension:input_type -> sliverpb.RegisterWasmExtensionReq
	118, // 165: rpcpb.SliverRPC.ListWasmExtensions:input_type -> sliverpb.ListWasmExtensionsReq
	119, // 166: rpcpb.SliverRPC.ExecWasmExtension:input_type -> sliverpb.ExecWasmExtensionReq
	120, // 167: rpcpb.SliverRPC.WGStartPortForward:input_type -> sliverpb.WGPortForwardStartReq
	121, // 168: rpcpb.SliverRPC.WGStopPortForward:input_type -> sliverpb.WGPortForwardStopReq
	122, // 169: rpcpb.SliverRPC.WGStartSocks:input_type -> sliverpb.WGSocksStartReq
	123, // 170: rpcpb.SliverRPC.WGStopSocks:input_type -> sliverpb.WGSocksStopReq
	124, // 171: rpcpb.SliverRPC.WGListForwarders:input_type -> sliverpb.WGTCPForwardersReq
	125, // 172: rpcpb.SliverRPC.WGListSocksServers:input_type -> sliverpb.WGSocksServersReq
	126, // 173: rpcpb.SliverRPC.Shell:input_type -> sliverpb.ShellReq
	127, // 174: rpcpb.SliverRPC.Portfwd:input_type -> sliverpb.PortfwdReq
	128, // 175: rpcpb.SliverRPC.CreateSocks:input_type -> sliverpb.Socks
	128, // 176: rpcpb.SliverRPC.CloseSocks:input_type -> sliverpb.Socks
	129, // 177: rpcpb.SliverRPC.SocksProxy:input_type -> sliverpb.SocksData
	130, // 178: rpcpb.SliverRPC.CreateTunnel:input_type -> sliverpb.Tunnel
	130, // 179: rpcpb.SliverRPC.CloseTunnel:input_type -> sliverpb.Tunnel
	131, // 180: rpcpb.SliverRPC.TunnelData:input_type -> sliverpb.TunnelData
	0,   // 181: rpcpb.SliverRPC.Events:input_type -> commonpb.Empty
	132, // 182: rpcpb.SliverRPC.GetVersion:output_type -> clientpb.Version
	0,   // 183: rpcpb.SliverRPC.ClientLog:output_type -> commonpb.Empty
	133, // 184: rpcpb.SliverRPC.GetOperators:output_type -> clientpb.Operators
	0,   // 185: rpcpb.SliverRPC.Kill:output_type -> commonpb.Empty
	134, // 186: rpcpb.SliverRPC.Reconfigure:output_type -> sliverpb.Reconfigure
	0,   // 187: rpcpb.SliverRPC.Rename:output_type -> commonpb.Empty
	135, // 188: rpcpb.SliverRPC.GetSessions:output_type -> clientpb.Sessions
	136, // 189: rpcpb.SliverRPC.MonitorStart:output_type -> commonpb.Response
	0,   // 190: rpcpb.SliverRPC.MonitorStop:output_type -> commonpb.Empty
	137, // 191: rpcpb.SliverRPC.MonitorListConfig:output_type -> clientpb.MonitoringProviders
	136, // 192: rpcpb.SliverRPC.MonitorAddConfig:output_type -> commonpb.Response
	136, // 193: rpcpb.SliverRPC.MonitorDelConfig:output_type -> commonpb.Response
	138, // 194: rpcpb.SliverRPC.StartMTLSListener:output_type -> clientpb.ListenerJob
	138, // 195: rpcpb.SliverRPC.StartWGListener:output_type -> clientpb.ListenerJob
	138, // 196: rpcpb.SliverRPC.StartDNSListener:output_type -> clientpb.ListenerJob
	138, // 197: rpcpb.SliverRPC.StartHTTPSListener:output_type -> clientpb.ListenerJob
	138, // 198: rpcpb.SliverRPC.StartHTTPListener:output_type -> clientpb.ListenerJob
	139, // 199: rpcpb.SliverRPC.GetBeacons:output_type -> clientpb.Beacons
	10,  // 200: rpcpb.SliverRPC.GetBeacon:output_type -> clientpb.Beacon
	0,   // 201: rpcpb.SliverRPC.RmBeacon:output_type -> commonpb.Empty
	140, // 202: rpcpb.SliverRPC.GetBeaconTasks:output_type -> clientpb.BeaconTasks
	11,  // 203: rpcpb.SliverRPC.GetBeaconTaskContent:output_type -> clientpb.BeaconTask
	11,  // 204: rpcpb.SliverRPC.CancelBeaconTask:output_type -> clientpb.BeaconTask
	0,   // 205: rpcpb.SliverRPC.UpdateBeaconIntegrityInformation:output_type -> commonpb.Empty
	141, // 206: rpcpb.SliverRPC.GetJobs:output_type -> clientpb.Jobs
	142, // 207: rpcpb.SliverRPC.KillJob:output_type -> clientpb.KillJob
	0,   // 208: rpcpb.SliverRPC.RestartJobs:output_type -> commonpb.Empty
	143, // 209: rpcpb.SliverRPC.StartTCPStagerListener:output_type -> clientpb.StagerListener
	16,  // 210: rpcpb.SliverRPC.LootAdd:output_type -> clientpb.Loot
	0,   // 211: rpcpb.SliverRPC.LootRm:output_type -> commonpb.Empty
	16,  // 212: rpcpb.SliverRPC.LootUpdate:output_type -> clientpb.Loot
	16,  // 213: rpcpb.SliverRPC.LootContent:output_type -> clientpb.Loot
	144, // 214: rpcpb.SliverRPC.LootAll:output_type -> clientpb.AllLoot
	17,  // 215: rpcpb.SliverRPC.Creds:output_type -> clientpb.Credentials
	0,   // 216: rpcpb.SliverRPC.CredsAdd:output_type -> commonpb.Empty
	0,   // 217: rpcpb.SliverRPC.CredsRm:output_type -> commonpb.Empty
	0,   // 218: rpcpb.SliverRPC.CredsUpdate:output_type -> commonpb.Empty
	18,  // 219: rpcpb.SliverRPC.GetCredByID:output_type -> clientpb.Credential
	17,  // 220: rpcpb.SliverRPC.GetCredsByHashType:output_type -> clientpb.Credentials
	17,  // 221: rpcpb.SliverRPC.GetPlaintextCredsByHashType:output_type -> clientpb.Credentials
	18,  // 222: rpcpb.SliverRPC.CredsSniffHashType:output_type -> clientpb.Credential
	145, // 223: rpcpb.SliverRPC.Hosts:output_type -> clientpb.AllHosts
	19,  // 224: rpcpb.SliverRPC.Host:output_type -> clientpb.Host
	0,   // 225: rpcpb.SliverRPC.HostRm:output_type -> commonpb.Empty
	0,   // 226: rpcpb.SliverRPC.HostIOCRm:output_type -> commonpb.Empty
	146, // 227: rpcpb.SliverRPC.HostScan:output_type -> clientpb.HostScanResults
	147, // 228: rpcpb.SliverRPC.Generate:output_type -> clientpb.Generate
	148, // 229: rpcpb.SliverRPC.GenerateExternal:output_type -> clientpb.ExternalImplantConfig
	0,   // 230: rpcpb.SliverRPC.GenerateExternalSaveBuild:output_type -> commonpb.Empty
	148, // 231: rpcpb.SliverRPC.GenerateExternalGetBuildConfig:output_type -> clientpb.ExternalImplantConfig
	147, // 232: rpcpb.SliverRPC.GenerateStage:output_type -> clientpb.Generate
	0,   // 233: rpcpb.SliverRPC.StageImplantBuild:output_type -> commonpb.Empty
	149, // 234: rpcpb.SliverRPC.GetHTTPC2Profiles:output_type -> clientpb.HTTPC2Configs
	150, // 235: rpcpb.SliverRPC.GetHTTPC2ProfileByName:output_type -> clientpb.HTTPC2Config
	0,   // 236: rpcpb.SliverRPC.SaveHTTPC2Profile:output_type -> commonpb.Empty
	31,  // 237: rpcpb.SliverRPC.BuilderRegister:output_type -> clientpb.Event
	0,   // 238: rpcpb.SliverRPC.BuilderTrigger:output_type -> commonpb.Empty
	151, // 239: rpcpb.SliverRPC.Builders:output_type -> clientpb.Builders
	152, // 240: rpcpb.SliverRPC.GetCertificateInfo:output_type -> clientpb.CertificateInfo
	31,  // 241: rpcpb.SliverRPC.CrackstationRegister:output_type -> clientpb.Event
	0,   // 242: rpcpb.SliverRPC.CrackstationTrigger:output_type -> commonpb.Empty
	0,   // 243: rpcpb.SliverRPC.CrackstationBenchmark:output_type -> commonpb.Empty
	153, // 244: rpcpb.SliverRPC.Crackstations:output_type -> clientpb.Crackstations
	35,  // 245: rpcpb.SliverRPC.CrackTaskByID:output_type -> clientpb.CrackTask
	0,   // 246: rpcpb.SliverRPC.CrackTaskUpdate:output_type -> commonpb.Empty
	154, // 247: rpcpb.SliverRPC.CrackFilesList:output_type -> clientpb.CrackFiles
	36,  // 248: rpcpb.SliverRPC.CrackFileCreate:output_type -> clientpb.CrackFile
	0,   // 249: rpcpb.SliverRPC.CrackFileChunkUpload:output_type -> commonpb.Empty
	37,  // 250: rpcpb.SliverRPC.CrackFileChunkDownload:output_type -> clientpb.CrackFileChunk
	0,   // 251: rpcpb.SliverRPC.CrackFileComplete:output_type -> commonpb.Empty
	0,   // 252: rpcpb.SliverRPC.CrackFileDelete:output_type -> commonpb.Empty
	147, // 253: rpcpb.SliverRPC.Regenerate:output_type -> clientpb.Generate
	155, // 254: rpcpb.SliverRPC.ImplantBuilds:output_type -> clientpb.ImplantBuilds
	0,   // 255: rpcpb.SliverRPC.DeleteImplantBuild:output_type -> commonpb.Empty
	156, // 256: rpcpb.SliverRPC.Canaries:output_type -> clientpb.Canaries
	157, // 257: rpcpb.SliverRPC.GenerateWGClientConfig:output_type -> clientpb.WGClientConfig
	158, // 258: rpcpb.SliverRPC.GenerateUniqueIP:output_type -> clientpb.UniqueWGIP
	159, // 259: rpcpb.SliverRPC.ImplantProfiles:output_type -> clientpb.ImplantProfiles
	0,   // 260: rpcpb.SliverRPC.DeleteImplantProfile:output_type -> commonpb.Empty
	40,  // 261: rpcpb.SliverRPC.SaveImplantProfile:output_type -> clientpb.ImplantProfile
	160, // 262: rpcpb.SliverRPC.ShellcodeRDI:output_type -> clientpb.ShellcodeRDI
	161, // 263: rpcpb.SliverRPC.GetCompiler:output_type -> clientpb.Compiler
	162, // 264: rpcpb.SliverRPC.ShellcodeEncoder:output_type -> clientpb.ShellcodeEncode
	163, // 265: rpcpb.SliverRPC.ShellcodeEncoderMap:output_type -> clientpb.ShellcodeEncoderMap
	164, // 266: rpcpb.SliverRPC.TrafficEncoderMap:output_type -> clientpb.TrafficEncoderMap
	165, // 267: rpcpb.SliverRPC.TrafficEncoderAdd:output_type -> clientpb.TrafficEncoderTests
	0,   // 268: rpcpb.SliverRPC.TrafficEncoderRm:output_type -> commonpb.Empty
	166, // 269: rpcpb.SliverRPC.Websites:output_type -> clientpb.Websites
	44,  // 270: rpcpb.SliverRPC.Website:output_type -> clientpb.Website
	0,   // 271: rpcpb.SliverRPC.WebsiteRemove:output_type -> commonpb.Empty
	44,  // 272: rpcpb.SliverRPC.WebsiteAddContent:output_type -> clientpb.Website
	44,  // 273: rpcpb.SliverRPC.WebsiteUpdateContent:output_type -> clientpb.Website
	44,  // 274: rpcpb.SliverRPC.WebsiteRemoveContent:output_type -> clientpb.Website
	47,  // 275: rpcpb.SliverRPC.Ping:output_type -> sliverpb.Ping
	167, // 276: rpcpb.SliverRPC.Ps:output_type -> sliverpb.Ps
	168, // 277: rpcpb.SliverRPC.Terminate:output_type -> sliverpb.Terminate
	169, // 278: rpcpb.SliverRPC.Ifconfig:output_type -> sliverpb.Ifconfig
	170, // 279: rpcpb.SliverRPC.Netstat:output_type -> sliverpb.Netstat
	171, // 280: rpcpb.SliverRPC.Ls:output_type -> sliverpb.Ls
	172, // 281: rpcpb.SliverRPC.Cd:output_type -> sliverpb.Pwd
	172, // 282: rpcpb.SliverRPC.Pwd:output_type -> sliverpb.Pwd
	173, // 283: rpcpb.SliverRPC.Mv:output_type -> sliverpb.Mv
	174, // 284: rpcpb.SliverRPC.Cp:output_type -> sliverpb.Cp
	175, // 285: rpcpb.SliverRPC.Rm:output_type -> sliverpb.Rm
	176, // 286: rpcpb.SliverRPC.Mkdir:output_type -> sliverpb.Mkdir
	177, // 287: rpcpb.SliverRPC.Download:output_type -> sliverpb.Download
	178, // 288: rpcpb.SliverRPC.Upload:output_type -> sliverpb.Upload
	179, // 289: rpcpb.SliverRPC.Grep:output_type -> sliverpb.Grep
	180, // 290: rpcpb.SliverRPC.Chmod:output_type -> sliverpb.Chmod
	181, // 291: rpcpb.SliverRPC.Chown:output_type -> sliverpb.Chown
	182, // 292: rpcpb.SliverRPC.Chtimes:output_type -> sliverpb.Chtimes
	171, // 293: rpcpb.SliverRPC.MemfilesList:output_type -> sliverpb.Ls
	183, // 294: rpcpb.SliverRPC.MemfilesAdd:output_type -> sliverpb.MemfilesAdd
	184, // 295: rpcpb.SliverRPC.MemfilesRm:output_type -> sliverpb.MemfilesRm
	185, // 296: rpcpb.SliverRPC.Mount:output_type -> sliverpb.Mount
	186, // 297: rpcpb.SliverRPC.ProcessDump:output_type -> sliverpb.ProcessDump
	187, // 298: rpcpb.SliverRPC.RunAs:output_type -> sliverpb.RunAs
	188, // 299: rpcpb.SliverRPC.Impersonate:output_type -> sliverpb.Impersonate
	189, // 300: rpcpb.SliverRPC.RevToSelf:output_type -> sliverpb.RevToSelf
	190, // 301: rpcpb.SliverRPC.GetSystem:output_type -> sliverpb.GetSystem
	191, // 302: rpcpb.SliverRPC.Task:output_type -> sliverpb.Task
	191, // 303: rpcpb.SliverRPC.Msf:output_type -> sliverpb.Task
	191, // 304: rpcpb.SliverRPC.MsfRemote:output_type -> sliverpb.Task
	192, // 305: rpcpb.SliverRPC.ExecuteAssembly:output_type -> sliverpb.ExecuteAssembly
	193, // 306: rpcpb.SliverRPC.Migrate:output_type -> sliverpb.Migrate
	194, // 307: rpcpb.SliverRPC.Execute:output_type -> sliverpb.Execute
	194, // 308: rpcpb.SliverRPC.ExecuteWindows:output_type -> sliverpb.Execute
	195, // 309: rpcpb.SliverRPC.Sideload:output_type -> sliverpb.Sideload
	196, // 310: rpcpb.SliverRPC.SpawnDll:output_type -> sliverpb.SpawnDll
	197, // 311: rpcpb.SliverRPC.Screenshot:output_type -> sliverpb.Screenshot
	198, // 312: rpcpb.SliverRPC.CurrentTokenOwner:output_type -> sliverpb.CurrentTokenOwner
	199, // 313: rpcpb.SliverRPC.Services:output_type -> sliverpb.Services
	200, // 314: rpcpb.SliverRPC.ServiceDetail:output_type -> sliverpb.ServiceDetail
	201, // 315: rpcpb.SliverRPC.StartServiceByName:output_type -> sliverpb.ServiceInfo
	202, // 316: rpcpb.SliverRPC.PivotStartListener:output_type -> sliverpb.PivotListener
	0,   // 317: rpcpb.SliverRPC.PivotStopListener:output_type -> commonpb.Empty
	203, // 318: rpcpb.SliverRPC.PivotSessionListeners:output_type -> sliverpb.PivotListeners
	204, // 319: rpcpb.SliverRPC.PivotGraph:output_type -> clientpb.PivotGraph
	201, // 320: rpcpb.SliverRPC.StartService:output_type -> sliverpb.ServiceInfo
	201, // 321: rpcpb.SliverRPC.StopService:output_type -> sliverpb.ServiceInfo
	201, // 322: rpcpb.SliverRPC.RemoveService:output_type -> sliverpb.ServiceInfo
	205, // 323: rpcpb.SliverRPC.MakeToken:output_type -> sliverpb.MakeToken
	206, // 324: rpcpb.SliverRPC.GetEnv:output_type -> sliverpb.EnvInfo
	207, // 325: rpcpb.SliverRPC.SetEnv:output_type -> sliverpb.SetEnv
	208, // 326: rpcpb.SliverRPC.UnsetEnv:output_type -> sliverpb.UnsetEnv
	209, // 327: rpcpb.SliverRPC.Backdoor:output_type -> clientpb.Backdoor
	210, // 328: rpcpb.SliverRPC.RegistryRead:output_type -> sliverpb.RegistryRead
	211, // 329: rpcpb.SliverRPC.RegistryWrite:output_type -> sliverpb.RegistryWrite
	212, // 330: rpcpb.SliverRPC.RegistryCreateKey:output_type -> sliverpb.RegistryCreateKey
	213, // 331: rpcpb.SliverRPC.RegistryDeleteKey:output_type -> sliverpb.RegistryDeleteKey
	214, // 332: rpcpb.SliverRPC.RegistryListSubKeys:output_type -> sliverpb.RegistrySubKeyList
	215, // 333: rpcpb.SliverRPC.RegistryListValues:output_type -> sliverpb.RegistryValuesList
	216, // 334: rpcpb.SliverRPC.RegistryReadHive:output_type -> sliverpb.RegistryReadHive
	217, // 335: rpcpb.SliverRPC.RunSSHCommand:output_type -> sliverpb.SSHCommand
	218, // 336: rpcpb.SliverRPC.HijackDLL:output_type -> clientpb.DllHijack
	219, // 337: rpcpb.SliverRPC.GetPrivs:output_type -> sliverpb.GetPrivs
	220, // 338: rpcpb.SliverRPC.StartRportFwdListener:output_type -> sliverpb.RportFwdListener
	221, // 339: rpcpb.SliverRPC.GetRportFwdListeners:output_type -> sliverpb.RportFwdListeners
	220, // 340: rpcpb.SliverRPC.StopRportFwdListener:output_type -> sliverpb.RportFwdListener
	112, // 341: rpcpb.SliverRPC.OpenSession:output_type -> sliverpb.OpenSession
	0,   // 342: rpcpb.SliverRPC.CloseSession:output_type -> commonpb.Empty
	222, // 343: rpcpb.SliverRPC.RegisterExtension:output_type -> sliverpb.RegisterExtension
	223, // 344: rpcpb.SliverRPC.CallExtension:output_type -> sliverpb.CallExtension
	224, // 345: rpcpb.SliverRPC.ListExtensions:output_type -> sliverpb.ListExtensions
	225, // 346: rpcpb.SliverRPC.RegisterWasmExtension:output_type -> sliverpb.RegisterWasmExtension
	226, // 347: rpcpb.SliverRPC.ListWasmExtensions:output_type -> sliverpb.ListWasmExtensions
	227, // 348: rpcpb.SliverRPC.ExecWasmExtension:output_type -> sliverpb.ExecWasmExtension
	228, // 349: rpcpb.SliverRPC.WGStartPortForward:output_type -> sliverpb.WGPortForward
	228, // 350: rpcpb.SliverRPC.WGStopPortForward:output_type -> sliverpb.WGPortForward
	229, // 351: rpcpb.SliverRPC.WGStartSocks:output_type -> sliverpb.WGSocks
	229, // 352: rpcpb.SliverRPC.WGStopSocks:output_type -> sliverpb.WGSocks
	230, // 353: rpcpb.SliverRPC.WGListForwarders:output_type -> sliverpb.WGTCPForwarders
	231, // 354: rpcpb.SliverRPC.WGListSocksServers:output_type -> sliverpb.WGSocksServers
	232, // 355: rpcpb.SliverRPC.Shell:output_type -> sliverpb.Shell
	233, // 356: rpcpb.SliverRPC.Portfwd:output_type -> sliverpb.Portfwd
	128, // 357: rpcpb.SliverRPC.CreateSocks:output_type -> sliverpb.Socks
	0,   // 358: rpcpb.SliverRPC.CloseSocks:output_type -> commonpb.Empty
	129, // 359: rpcpb.SliverRPC.SocksProxy:output_type -> sliverpb.SocksData
	130, // 360: rpcpb.SliverRPC.CreateTunnel:output_type -> sliverpb.Tunnel
	0,   // 361: rpcpb.SliverRPC.CloseTunnel:output_type -> commonpb.Empty
	131, // 362: rpcpb.SliverRPC.TunnelData:output_type -> sliverpb.TunnelData
	31,  // 363: rpcpb.SliverRPC.Events:output_type -> clientpb.Event
	182, // [182:364] is the sub-list for method output_type
	0,   // [0:182] is the sub-list for method input_type
	0,   // [0:0] is the sub-list for extension type_name
	0,   // [0:0] is the sub-list for extension extendee
	0,   // [0:0] is the sub-list for field type_name
}

func init() { file_rpcpb_services_proto_init() }
func file_rpcpb_services_proto_init() {
	if File_rpcpb_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpcpb_services_proto_rawDesc), len(file_rpcpb_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcpb_services_proto_goTypes,
		DependencyIndexes: file_rpcpb_services_proto_depIdxs,
	}.Build()
	File_rpcpb_services_proto = out.File
	file_rpcpb_services_proto_goTypes = nil
	file_rpcpb_services_proto_depIdxs = nil
}
